spring:
  application:
    name: cloudserviceregistery

server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  endpoint:
    health:
      show-details: always    
    
    
  
  
    
    
    
    
    
    