spring:
  application:
    name: orderservice
  boot:
    admin:
      client:
        url: http://adminserver:1111/
           
server:
  port: 9091
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://serviceregistery:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://zipkin:9411